[workspace]

members = [
    "jyutping-microservice",
    "wordseg",
    "rscantonese",
    "wasmcantonese",
    "chat-parser",
    "variant-map-parser"
]

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true

[profile.release.package.wasmcantonese]
opt-level = "s"
