[workspace]

members = [
    "jyutping-microservice",
    "rscantonese",
    "wikitext-cleaner"
]

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true

# [profile.release.package.wasmcantonese]
# opt-level = "s"
