[package]
name = "rscantonese"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wordseg = { path = "../wordseg"}
chat-parser = { path = "../chat-parser"}
# Dependencies for seralizing words.hk data
serde_json = "1.0.79"
serde = "1.0.136"

[dev-dependencies]
criterion = "0.3.5"
