[package]
name = "wikitext-cleaner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom-unicode = "0.3.0"
nom = { version = "7.1.1" }
clap = { version = "3.1.8", features = ["derive"] }
