#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GIT_ROOT=$(git rev-parse --show-toplevel);
WEB_ROOT="$GIT_ROOT/web";
HELPER_ROOT="$GIT_ROOT/jyutping-helpers"

# WEB
# "$WEB_ROOT/node_modules/.bin/svelte-check"
"$WEB_ROOT/node_modules/.bin/lint-staged" --cwd "$WEB_ROOT"

# HELPER
"$HELPER_ROOT/node_modules/.bin/tsc-files" --noEmit
"$HELPER_ROOT/node_modules/.bin/lint-staged" --cwd "$HELPER_ROOT"
