#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GIT_ROOT=$(git rev-parse --show-toplevel);
WEB_ROOT="$GIT_ROOT/web";
HELPER_ROOT="$GIT_ROOT/jyutping-helpers"

"$WEB_ROOT/node_modules/.bin/lint-staged" --cwd "$WEB_ROOT"
"$HELPER_ROOT/node_modules/.bin/lint-staged" --cwd "$HELPER_ROOT"
