export default {
	VITE_MICROSERVICE_URL: import.meta.env.VITE_MICROSERVICE_URL,
	VITE_MICROSERVICE_USER: import.meta.env.VITE_MICROSERVICE_USER,
	VITE_MICROSERVICE_PWD: import.meta.env.VITE_MICROSERVICE_PWD
};
