export default {
	VITE_MICROSERVICE_URL: import.meta.env.VITE_MICROSERVICE_URL,
	VITE_MICROSERVICE_USER: import.meta.env.VITE_MICROSERVICE_USER,
	VITE_MICROSERVICE_PWD: import.meta.env.VITE_MICROSERVICE_PWD,
	VITE_BUILD_TIME: import.meta.env.VITE_BUILD_TIME
};
