---
name: Process wikidump data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 3,22 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: "Install wikiextractor"
        run: pip install wikiextractor

      - name: "Fetch wiki dump file"
        run: curl -o ./rscantonese/data/wikidump/latest.xml.bz2 https://dumps.wikimedia.org/zh_yuewiki/latest/zh_yuewiki-latest-pages-articles.xml.bz2
      
      - name: "Decompress file"
        run: bzip2 -d ./rscantonese/data/wikidump/latest.xml.bz2
      