---
name: Release wikitext-cleaner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p wikitext-cleaner --release --all-features
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get short hash
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # automatic_release_tag: "${{ steps.vars.outputs.sha_short }}"
          # Use latest as tag for now
          automatic_release_tag: "latest"
          prerelease: true
          title: "wikitext-extractor(${{ steps.date.outputs.date }})"
          files: |
            ./target/release/wikitext-cleaner